#ifndef AFE4960_EX_INCLUDED
#define AFE4960_EX_INCLUDED

#define AFE4960_DESIGN_ID (0x101)
typedef enum {
    CONFIG_TSM_DUMMY = 0,
    CONFIG_TSM_ECG,
    CONFIG_TSM_DO_NOT_USE,
    CONFIG_TSM_BIOZ
} config_tsm_e;

#define COUNT_RAC_TO_LEAD_DET_WIDTH(rac_count, num_esaw) (((10 * rac_count)/num_esaw)>>7)
typedef enum {
    COUNT_RAC_1000SA_SEC = 0x080,
    COUNT_RAC_500SA_SEC = 0x100,
    COUNT_RAC_250SA_SEC = 0x200,
    COUNT_RAC_125SA_SEC = 0x400,
    COUNT_RAC_62_5SA_SEC = 0x800
} count_rac_t;

typedef enum {
    RBIAS_100MOHM = 0,
    RBIAS_50MOHM,
    RBIAS_25MOHM,
    RBIAS_12_5MOHM,
    RBIAS_6_25MOHM
} rbias_sel_t;

typedef enum {
    POL_RBIAS_0_15V = 0,
    POL_RBIAS_1_65V
} pol_rbias_t;

typedef enum {
    LEAD_DET_THR_L_0_55V = 3,
    LEAD_DET_THR_L_0_60V = 4,
    LEAD_DET_THR_L_0_65V = 5
} lead_det_thr_l_t;

typedef enum {
    LEAD_DET_THR_H_1_25V = 3,
    LEAD_DET_THR_H_1_20V = 4,
    LEAD_DET_THR_H_1_15V = 5
} lead_det_thr_h_t;

typedef enum {
    SW_ECG4 = 1,
    SW_ECG3 = 2,
    SW_ECG1 = 4,
    SW_ECG2 = 8
} sw_ecg_t;

typedef enum {
    SW_RESP1 = 1,
    SW_RESP2 = 2,
    SW_RESP3 = 4,
    SW_RESP4 = 8
} sw_resp_t;

typedef enum {
    INA_GAIN_3 = 0,
    INA_GAIN_2,
    INA_GAIN_4,
    INA_GAIN_5,
    INA_GAIN_6,
    INA_GAIN_9,
    INA_GAIN_12
} ina_gain_t;

typedef enum {
    BIOZ_INA_GAIN_2 = 0,
    BIOZ_INA_GAIN_3,
    BIOZ_INA_GAIN_5,
    BIOZ_INA_GAIN_9,
    BIOZ_INA_GAIN_12,
    BIOZ_INA_GAIN_DNU1,
    BIOZ_INA_GAIN_DNU2,
    BIOZ_INA_GAIN_DNU3
} bioz_ina_gain_t;

typedef enum {
    BIOZ_LPF_BW_1_2KHZ = 0,
    BIOZ_LPF_BW_DNU1,
    BIOZ_LPF_BW_370HZ,
    BIOZ_LPF_BW_DNU2
} bioz_lpf_bw_t;

typedef enum {
    SW_BIOZ_OUT_NC = 0,
    SW_BIOZ_OUT_RESP1,
    SW_BIOZ_OUT_RESP2,
    SW_BIOZ_OUT_RESP3,
    SW_BIOZ_OUT_RESP4,
    SW_BIOZ_OUT_ECG1,
    SW_BIOZ_OUT_ECG2,
    SW_BIOZ_OUT_ECG4,
    SW_BIOZ_OUT_ECG3
} sw_bioz_out_t;

typedef enum {
    SW_BIOZ_IN_VCM = 0,
    SW_BIOZ_IN_RESP1,
    SW_BIOZ_IN_RESP2,
    SW_BIOZ_IN_RESP3,
    SW_BIOZ_IN_RESP4,
    SW_BIOZ_IN_ECG1,
    SW_BIOZ_IN_ECG2,
    SW_BIOZ_IN_ECG4,
    SW_BIOZ_IN_ECG3
} sw_bioz_in_t;

typedef enum {
    IBIAS_12_5NA = 3,
    IBIAS_25NA,
    IBIAS_50NA,
    IBIAS_100NA
} ibias_setting_t;

typedef enum {
    IBIAS_BIAS_AMPL_FOR_12_5NA = 3,
    IBIAS_BIAS_AMPL_FOR_25NA = 5,
    IBIAS_BIAS_AMPL_FOR_50NA = 9,
    IBIAS_BIAS_AMPL_FOR_100NA = 25
} ibias_bias_ampl_setting_t;

typedef enum {
    DEC_FACTOR_2 = 0,
    DEC_FACTOR_4,
    DEC_FACTOR_8,
    DEC_FACTOR_16,
    DEC_FACTOR_32
} dec_factor_t;

#define CONTROL0_ADDR ( 0 )
#define SPI_REG_READ_BITPOS ( 0 )
#define SPI_REG_READ_FIELDWIDTH ( 1 )
#define SPI_REG_READ_MASK ( ((1<<SPI_REG_READ_FIELDWIDTH)-1)<<SPI_REG_READ_BITPOS )
#define TM_COUNT_RST_BITPOS ( 1 )
#define TM_COUNT_RST_FIELDWIDTH ( 1 )
#define TM_COUNT_RST_MASK ( ((1<<TM_COUNT_RST_FIELDWIDTH)-1)<<TM_COUNT_RST_BITPOS )
#define SW_RESET_BITPOS ( 3 )
#define SW_RESET_FIELDWIDTH ( 1 )
#define SW_RESET_MASK ( ((1<<SW_RESET_FIELDWIDTH)-1)<<SW_RESET_BITPOS )
#define RW_CONT_BITPOS ( 4 )
#define RW_CONT_FIELDWIDTH ( 1 )
#define RW_CONT_MASK ( ((1<<RW_CONT_FIELDWIDTH)-1)<<RW_CONT_BITPOS )
#define FIFO_EN_BITPOS ( 6 )
#define FIFO_EN_FIELDWIDTH ( 1 )
#define FIFO_EN_MASK ( ((1<<FIFO_EN_FIELDWIDTH)-1)<<FIFO_EN_BITPOS )

#define CONTROL2_ADDR ( 2 )
#define INT_MUX_GPIO2_1_BITPOS ( 0 )
#define INT_MUX_GPIO2_1_FIELDWIDTH ( 2 )
#define INT_MUX_GPIO2_1_MASK ( ((1<<INT_MUX_GPIO2_1_FIELDWIDTH)-1)<<INT_MUX_GPIO2_1_BITPOS )

#define CONFIG_MODE_SEL_ADDR ( 10 )
#define ACQ_MODE_SEL_BITPOS ( 0 )
#define ACQ_MODE_SEL_FIELDWIDTH ( 7 )
#define ACQ_MODE_SEL_MASK ( ((1<<ACQ_MODE_SEL_FIELDWIDTH)-1)<<ACQ_MODE_SEL_BITPOS )
#define EN_BIOZ_TX_BITPOS ( 18 )
#define EN_BIOZ_TX_FIELDWIDTH ( 1 )
#define EN_BIOZ_TX_MASK ( ((1<<EN_BIOZ_TX_FIELDWIDTH)-1)<<EN_BIOZ_TX_BITPOS )
#define EN_BIOZ_RX_BITPOS ( 20 )
#define EN_BIOZ_RX_FIELDWIDTH ( 1 )
#define EN_BIOZ_RX_MASK ( ((1<<EN_BIOZ_RX_FIELDWIDTH)-1)<<EN_BIOZ_RX_BITPOS )
#define EN_ECG_RX_BITPOS ( 23 )
#define EN_ECG_RX_FIELDWIDTH ( 1 )
#define EN_ECG_RX_MASK ( ((1<<EN_ECG_RX_FIELDWIDTH)-1)<<EN_ECG_RX_BITPOS )

#define ACT_CTRL_ADDR ( 11 )
#define PDN_OSCH_BITPOS ( 8 )
#define PDN_OSCH_FIELDWIDTH ( 1 )
#define PDN_OSCH_MASK ( ((1<<PDN_OSCH_FIELDWIDTH)-1)<<PDN_OSCH_BITPOS )
#define PDN_ADC_BITPOS ( 10 )
#define PDN_ADC_FIELDWIDTH ( 1 )
#define PDN_ADC_MASK ( ((1<<PDN_ADC_FIELDWIDTH)-1)<<PDN_ADC_BITPOS )
#define PDN_ECG_INA_BITPOS ( 14 )
#define PDN_ECG_INA_FIELDWIDTH ( 1 )
#define PDN_ECG_INA_MASK ( ((1<<PDN_ECG_INA_FIELDWIDTH)-1)<<PDN_ECG_INA_BITPOS )
#define PDN_ECG_RLD_BITPOS ( 16 )
#define PDN_ECG_RLD_FIELDWIDTH ( 1 )
#define PDN_ECG_RLD_MASK ( ((1<<PDN_ECG_RLD_FIELDWIDTH)-1)<<PDN_ECG_RLD_BITPOS )

#define CTRL_PDN_ADDR ( 12 )
#define PDN_ILEAD_BITPOS ( 0 )
#define PDN_ILEAD_FIELDWIDTH ( 1 )
#define PDN_ILEAD_MASK ( ((1<<PDN_ILEAD_FIELDWIDTH)-1)<<PDN_ILEAD_BITPOS )
#define DIS_ACTIVE_BIOZ_TX_BITPOS ( 4 )
#define DIS_ACTIVE_BIOZ_TX_FIELDWIDTH ( 1 )
#define DIS_ACTIVE_BIOZ_TX_MASK ( ((1<<DIS_ACTIVE_BIOZ_TX_FIELDWIDTH)-1)<<DIS_ACTIVE_BIOZ_TX_BITPOS )
#define DIS_PD_REFSYS_BITPOS ( 16 )
#define DIS_PD_REFSYS_FIELDWIDTH ( 1 )
#define DIS_PD_REFSYS_MASK ( ((1<<DIS_PD_REFSYS_FIELDWIDTH)-1)<<DIS_PD_REFSYS_BITPOS )
#define DIS_PD_VCM_BITPOS ( 19 )
#define DIS_PD_VCM_FIELDWIDTH ( 1 )
#define DIS_PD_VCM_MASK ( ((1<<DIS_PD_VCM_FIELDWIDTH)-1)<<DIS_PD_VCM_BITPOS )
#define PDN_BG_IN_DEEP_SLEEP_BITPOS ( 21 )
#define PDN_BG_IN_DEEP_SLEEP_FIELDWIDTH ( 1 )
#define PDN_BG_IN_DEEP_SLEEP_MASK ( ((1<<PDN_BG_IN_DEEP_SLEEP_FIELDWIDTH)-1)<<PDN_BG_IN_DEEP_SLEEP_BITPOS )

#define RAC_CONTROL_ADDR ( 29 )
#define RAC_COUNTER_ENABLE_BITPOS ( 22 )
#define RAC_COUNTER_ENABLE_FIELDWIDTH ( 1 )
#define RAC_COUNTER_ENABLE_MASK ( ((1<<RAC_COUNTER_ENABLE_FIELDWIDTH)-1)<<RAC_COUNTER_ENABLE_BITPOS )
#define TIMER_ENABLE_BITPOS ( 23 )
#define TIMER_ENABLE_FIELDWIDTH ( 1 )
#define TIMER_ENABLE_MASK ( ((1<<TIMER_ENABLE_FIELDWIDTH)-1)<<TIMER_ENABLE_BITPOS )

#define CONTROL4_ADDR ( 35 )
#define PDNAFE_BITPOS ( 0 )
#define PDNAFE_FIELDWIDTH ( 1 )
#define PDNAFE_MASK ( ((1<<PDNAFE_FIELDWIDTH)-1)<<PDNAFE_BITPOS )

#define READ_DESIGNID_ADDR ( 40 )
#define DESIGN_ID_BITPOS ( 7 )
#define DESIGN_ID_FIELDWIDTH ( 13 )
#define DESIGN_ID_MASK ( ((1<<DESIGN_ID_FIELDWIDTH)-1)<<DESIGN_ID_BITPOS )

#define CONTROL7_ADDR ( 41 )
#define SDOUT_TRISTATE_BITPOS ( 10 )
#define SDOUT_TRISTATE_FIELDWIDTH ( 1 )
#define SDOUT_TRISTATE_MASK ( ((1<<SDOUT_TRISTATE_FIELDWIDTH)-1)<<SDOUT_TRISTATE_BITPOS )
#define EN_GPIO2_OUT_BITPOS ( 19 )
#define EN_GPIO2_OUT_FIELDWIDTH ( 1 )
#define EN_GPIO2_OUT_MASK ( ((1<<EN_GPIO2_OUT_FIELDWIDTH)-1)<<EN_GPIO2_OUT_BITPOS )
#define EN_GPIO2_INT_ON_ADC_RDY_BITPOS ( 23 )
#define EN_GPIO2_INT_ON_ADC_RDY_FIELDWIDTH ( 1 )
#define EN_GPIO2_INT_ON_ADC_RDY_MASK ( ((1<<EN_GPIO2_INT_ON_ADC_RDY_FIELDWIDTH)-1)<<EN_GPIO2_INT_ON_ADC_RDY_BITPOS )

#define CONTROL8_ADDR ( 49 )
#define EN_GPIO2_IN_BITPOS ( 14 )
#define EN_GPIO2_IN_FIELDWIDTH ( 1 )
#define EN_GPIO2_IN_MASK ( ((1<<EN_GPIO2_IN_FIELDWIDTH)-1)<<EN_GPIO2_IN_BITPOS )

#define INA_GAIN_ERROR_ADDR ( 56 )
#define INA_GAIN_ERROR_CH1_BITPOS ( 0 )
#define INA_GAIN_ERROR_CH1_FIELDWIDTH ( 7 )
#define INA_GAIN_ERROR_CH1_MASK ( ((1<<INA_GAIN_ERROR_CH1_FIELDWIDTH)-1)<<INA_GAIN_ERROR_CH1_BITPOS )
#define INA_GAIN_ERROR_CH2_BITPOS ( 12 )
#define INA_GAIN_ERROR_CH2_FIELDWIDTH ( 7 )
#define INA_GAIN_ERROR_CH2_MASK ( ((1<<INA_GAIN_ERROR_CH2_FIELDWIDTH)-1)<<INA_GAIN_ERROR_CH2_BITPOS )

#define CONTROL9_ADDR ( 66 )
#define INT_MUX_ADC_RDY_1_BITPOS ( 4 )
#define INT_MUX_ADC_RDY_1_FIELDWIDTH ( 2 )
#define INT_MUX_ADC_RDY_1_MASK ( ((1<<INT_MUX_ADC_RDY_1_FIELDWIDTH)-1)<<INT_MUX_ADC_RDY_1_BITPOS )
#define REG_WM_FIFO_BITPOS ( 6 )
#define REG_WM_FIFO_FIELDWIDTH ( 8 )
#define REG_WM_FIFO_MASK ( ((1<<REG_WM_FIFO_FIELDWIDTH)-1)<<REG_WM_FIFO_BITPOS )
#define EN_PACE_WINDOW_GPIO2_BITPOS ( 14 )
#define EN_PACE_WINDOW_GPIO2_FIELDWIDTH ( 1 )
#define EN_PACE_WINDOW_GPIO2_MASK ( ((1<<EN_PACE_WINDOW_GPIO2_FIELDWIDTH)-1)<<EN_PACE_WINDOW_GPIO2_BITPOS )
#define EN_PACE_WINDOW_ADC_RDY_BITPOS ( 15 )
#define EN_PACE_WINDOW_ADC_RDY_FIELDWIDTH ( 1 )
#define EN_PACE_WINDOW_ADC_RDY_MASK ( ((1<<EN_PACE_WINDOW_ADC_RDY_FIELDWIDTH)-1)<<EN_PACE_WINDOW_ADC_RDY_BITPOS )
#define INT_MUX_ADC_RDY_2_BITPOS ( 16 )
#define INT_MUX_ADC_RDY_2_FIELDWIDTH ( 1 )
#define INT_MUX_ADC_RDY_2_MASK ( ((1<<INT_MUX_ADC_RDY_2_FIELDWIDTH)-1)<<INT_MUX_ADC_RDY_2_BITPOS )
#define INT_MUX_GPIO_2_BITPOS ( 19 )
#define INT_MUX_GPIO_2_FIELDWIDTH ( 1 )
#define INT_MUX_GPIO_2_MASK ( ((1<<INT_MUX_GPIO_2_FIELDWIDTH)-1)<<INT_MUX_GPIO_2_BITPOS )

#define CONTROL10_ADDR ( 75 )
#define DIS_BUF_PDN_ON_ADC_BITPOS ( 8 )
#define DIS_BUF_PDN_ON_ADC_FIELDWIDTH ( 1 )
#define DIS_BUF_PDN_ON_ADC_MASK ( ((1<<DIS_BUF_PDN_ON_ADC_FIELDWIDTH)-1)<<DIS_BUF_PDN_ON_ADC_BITPOS )
#define EN_128K_CLKOUT_BITPOS ( 22 )
#define EN_128K_CLKOUT_FIELDWIDTH ( 1 )
#define EN_128K_CLKOUT_MASK ( ((1<<EN_128K_CLKOUT_FIELDWIDTH)-1)<<EN_128K_CLKOUT_BITPOS )

#define CONTROL13_ADDR ( 81 )
#define FIFO_OFFSET_TO_FORCE_BITPOS ( 0 )
#define FIFO_OFFSET_TO_FORCE_FIELDWIDTH ( 8 )
#define FIFO_OFFSET_TO_FORCE_MASK ( ((1<<FIFO_OFFSET_TO_FORCE_FIELDWIDTH)-1)<<FIFO_OFFSET_TO_FORCE_BITPOS )
#define FORCE_FIFO_OFFSET_BITPOS ( 8 )
#define FORCE_FIFO_OFFSET_FIELDWIDTH ( 1 )
#define FORCE_FIFO_OFFSET_MASK ( ((1<<FORCE_FIFO_OFFSET_FIELDWIDTH)-1)<<FORCE_FIFO_OFFSET_BITPOS )
#define MASK_FIFO_RDY_BITPOS ( 9 )
#define MASK_FIFO_RDY_FIELDWIDTH ( 1 )
#define MASK_FIFO_RDY_MASK ( ((1<<MASK_FIFO_RDY_FIELDWIDTH)-1)<<MASK_FIFO_RDY_BITPOS )
#define AUTO_MASK_FIFO_RDY_BITPOS ( 10 )
#define AUTO_MASK_FIFO_RDY_FIELDWIDTH ( 1 )
#define AUTO_MASK_FIFO_RDY_MASK ( ((1<<AUTO_MASK_FIFO_RDY_FIELDWIDTH)-1)<<AUTO_MASK_FIFO_RDY_BITPOS )

#define READ_POINTER_ADDR ( 109 )
#define REG_POINTER_DIFF_BITPOS ( 0 )
#define REG_POINTER_DIFF_FIELDWIDTH ( 8 )
#define REG_POINTER_DIFF_MASK ( ((1<<REG_POINTER_DIFF_FIELDWIDTH)-1)<<REG_POINTER_DIFF_BITPOS )

#define CONTROL19_ADDR ( 117 )
#define PACE_DIS_RESP_REJECT_BITPOS ( 19 )
#define PACE_DIS_RESP_REJECT_FIELDWIDTH ( 1 )
#define PACE_DIS_RESP_REJECT_MASK ( ((1<<PACE_DIS_RESP_REJECT_FIELDWIDTH)-1)<<PACE_DIS_RESP_REJECT_BITPOS )

#define CONTROL20_ADDR ( 136 )
#define MODE_EN_FRAME_SYNC_BITPOS ( 6 )
#define MODE_EN_FRAME_SYNC_FIELDWIDTH ( 1 )
#define MODE_EN_FRAME_SYNC_MASK ( ((1<<MODE_EN_FRAME_SYNC_FIELDWIDTH)-1)<<MODE_EN_FRAME_SYNC_BITPOS )

#define READ_AC_LEAD_ADDR ( 182 )
#define AC_LEAD_AMPL_BITPOS ( 0 )
#define AC_LEAD_AMPL_FIELDWIDTH ( 24 )
#define AC_LEAD_AMPL_MASK ( ((1<<AC_LEAD_AMPL_FIELDWIDTH)-1)<<AC_LEAD_AMPL_BITPOS )

#define AC_DEMOD_ADDR ( 184 )
#define ECG_SAMPLE_SIGN_BITPOS ( 0 )
#define ECG_SAMPLE_SIGN_FIELDWIDTH ( 16 )
#define ECG_SAMPLE_SIGN_MASK ( ((1<<ECG_SAMPLE_SIGN_FIELDWIDTH)-1)<<ECG_SAMPLE_SIGN_BITPOS )
#define AC_LEAD_DEMOD_CFG_BITPOS ( 16 )
#define AC_LEAD_DEMOD_CFG_FIELDWIDTH ( 8 )
#define AC_LEAD_DEMOD_CFG_MASK ( ((1<<AC_LEAD_DEMOD_CFG_FIELDWIDTH)-1)<<AC_LEAD_DEMOD_CFG_BITPOS )

#define MASK_INT_REG_ADDR ( 187 )
#define MASK_DC_LEAD_DET_BITPOS ( 0 )
#define MASK_DC_LEAD_DET_FIELDWIDTH ( 1 )
#define MASK_DC_LEAD_DET_MASK ( ((1<<MASK_DC_LEAD_DET_FIELDWIDTH)-1)<<MASK_DC_LEAD_DET_BITPOS )
#define MASK_AC_LEAD_ON_BITPOS ( 1 )
#define MASK_AC_LEAD_ON_FIELDWIDTH ( 1 )
#define MASK_AC_LEAD_ON_MASK ( ((1<<MASK_AC_LEAD_ON_FIELDWIDTH)-1)<<MASK_AC_LEAD_ON_BITPOS )
#define MASK_AC_LEAD_OFF_BITPOS ( 2 )
#define MASK_AC_LEAD_OFF_FIELDWIDTH ( 1 )
#define MASK_AC_LEAD_OFF_MASK ( ((1<<MASK_AC_LEAD_OFF_FIELDWIDTH)-1)<<MASK_AC_LEAD_OFF_BITPOS )
#define MASK_ADC_FIFO_RDY_BITPOS ( 3 )
#define MASK_ADC_FIFO_RDY_FIELDWIDTH ( 1 )
#define MASK_ADC_FIFO_RDY_MASK ( ((1<<MASK_ADC_FIFO_RDY_FIELDWIDTH)-1)<<MASK_ADC_FIFO_RDY_BITPOS )
#define MASK_DISABLE1_BITPOS ( 4 )
#define MASK_DISABLE1_FIELDWIDTH ( 1 )
#define MASK_DISABLE1_MASK ( ((1<<MASK_DISABLE1_FIELDWIDTH)-1)<<MASK_DISABLE1_BITPOS )
#define MASK_DISABLE2_BITPOS ( 5 )
#define MASK_DISABLE2_FIELDWIDTH ( 1 )
#define MASK_DISABLE2_MASK ( ((1<<MASK_DISABLE2_FIELDWIDTH)-1)<<MASK_DISABLE2_BITPOS )
#define MASK_PACE_VALID_INT_BITPOS ( 6 )
#define MASK_PACE_VALID_INT_FIELDWIDTH ( 1 )
#define MASK_PACE_VALID_INT_MASK ( ((1<<MASK_PACE_VALID_INT_FIELDWIDTH)-1)<<MASK_PACE_VALID_INT_BITPOS )

#define INTR_SOFT_ADDR ( 188 )
#define LEAD_STATUS4_BITPOS ( 8 )
#define LEAD_STATUS4_FIELDWIDTH ( 1 )
#define LEAD_STATUS4_MASK ( ((1<<LEAD_STATUS4_FIELDWIDTH)-1)<<LEAD_STATUS4_BITPOS )
#define LEAD_STATUS3_BITPOS ( 9 )
#define LEAD_STATUS3_FIELDWIDTH ( 1 )
#define LEAD_STATUS3_MASK ( ((1<<LEAD_STATUS3_FIELDWIDTH)-1)<<LEAD_STATUS3_BITPOS )
#define LEAD_STATUS2_BITPOS ( 10 )
#define LEAD_STATUS2_FIELDWIDTH ( 1 )
#define LEAD_STATUS2_MASK ( ((1<<LEAD_STATUS2_FIELDWIDTH)-1)<<LEAD_STATUS2_BITPOS )
#define LEAD_STATUS1_BITPOS ( 11 )
#define LEAD_STATUS1_FIELDWIDTH ( 1 )
#define LEAD_STATUS1_MASK ( ((1<<LEAD_STATUS1_FIELDWIDTH)-1)<<LEAD_STATUS1_BITPOS )
#define PACE_STATUS_BITPOS ( 20 )
#define PACE_STATUS_FIELDWIDTH ( 1 )
#define PACE_STATUS_MASK ( ((1<<PACE_STATUS_FIELDWIDTH)-1)<<PACE_STATUS_BITPOS )
#define AC_LEAD_STATUS_BITPOS ( 22 )
#define AC_LEAD_STATUS_FIELDWIDTH ( 2 )
#define AC_LEAD_STATUS_MASK ( ((1<<AC_LEAD_STATUS_FIELDWIDTH)-1)<<AC_LEAD_STATUS_BITPOS )

#define CONTROL25_ADDR ( 190 )
#define EN_PACE_TAG_ECG_CH1_BITPOS ( 0 )
#define EN_PACE_TAG_ECG_CH1_FIELDWIDTH ( 1 )
#define EN_PACE_TAG_ECG_CH1_MASK ( ((1<<EN_PACE_TAG_ECG_CH1_FIELDWIDTH)-1)<<EN_PACE_TAG_ECG_CH1_BITPOS )
#define EN_PACE_TAG_ECG_CH2_BITPOS ( 1 )
#define EN_PACE_TAG_ECG_CH2_FIELDWIDTH ( 1 )
#define EN_PACE_TAG_ECG_CH2_MASK ( ((1<<EN_PACE_TAG_ECG_CH2_FIELDWIDTH)-1)<<EN_PACE_TAG_ECG_CH2_BITPOS )
#define EN_PACE_VALID_TAG_BITPOS ( 2 )
#define EN_PACE_VALID_TAG_FIELDWIDTH ( 1 )
#define EN_PACE_VALID_TAG_MASK ( ((1<<EN_PACE_VALID_TAG_FIELDWIDTH)-1)<<EN_PACE_VALID_TAG_BITPOS )
#define EN_PACE_OVERLAP_TAG_BITPOS ( 3 )
#define EN_PACE_OVERLAP_TAG_FIELDWIDTH ( 1 )
#define EN_PACE_OVERLAP_TAG_MASK ( ((1<<EN_PACE_OVERLAP_TAG_FIELDWIDTH)-1)<<EN_PACE_OVERLAP_TAG_BITPOS )
#define USE_PACE_OVERLAP_TAG_BITPOS ( 4 )
#define USE_PACE_OVERLAP_TAG_FIELDWIDTH ( 1 )
#define USE_PACE_OVERLAP_TAG_MASK ( ((1<<USE_PACE_OVERLAP_TAG_FIELDWIDTH)-1)<<USE_PACE_OVERLAP_TAG_BITPOS )
#define USE_BOTH_PACE_TAGS_BITPOS ( 5 )
#define USE_BOTH_PACE_TAGS_FIELDWIDTH ( 1 )
#define USE_BOTH_PACE_TAGS_MASK ( ((1<<USE_BOTH_PACE_TAGS_FIELDWIDTH)-1)<<USE_BOTH_PACE_TAGS_BITPOS )
#define PACE_FIFO_DATA_CTRL_BITPOS ( 6 )
#define PACE_FIFO_DATA_CTRL_FIELDWIDTH ( 2 )
#define PACE_FIFO_DATA_CTRL_MASK ( ((1<<PACE_FIFO_DATA_CTRL_FIELDWIDTH)-1)<<PACE_FIFO_DATA_CTRL_BITPOS )
#define INPUT_OUTPUT_RAC_RST_BITPOS ( 16 )
#define INPUT_OUTPUT_RAC_RST_FIELDWIDTH ( 2 )
#define INPUT_OUTPUT_RAC_RST_MASK ( ((1<<INPUT_OUTPUT_RAC_RST_FIELDWIDTH)-1)<<INPUT_OUTPUT_RAC_RST_BITPOS )
#define EN_DATA_MARKER_BITPOS ( 22 )
#define EN_DATA_MARKER_FIELDWIDTH ( 1 )
#define EN_DATA_MARKER_MASK ( ((1<<EN_DATA_MARKER_FIELDWIDTH)-1)<<EN_DATA_MARKER_BITPOS )

#define CONFIG_CLK_CKT_MIX1_ADDR ( 191 )
#define SEL1_CLK_TE_BITPOS ( 0 )
#define SEL1_CLK_TE_FIELDWIDTH ( 1 )
#define SEL1_CLK_TE_MASK ( ((1<<SEL1_CLK_TE_FIELDWIDTH)-1)<<SEL1_CLK_TE_BITPOS )
#define SEL2_CLK_TE_BITPOS ( 1 )
#define SEL2_CLK_TE_FIELDWIDTH ( 1 )
#define SEL2_CLK_TE_MASK ( ((1<<SEL2_CLK_TE_FIELDWIDTH)-1)<<SEL2_CLK_TE_BITPOS )
#define OSCL_DIS_BITPOS ( 2 )
#define OSCL_DIS_FIELDWIDTH ( 1 )
#define OSCL_DIS_MASK ( ((1<<OSCL_DIS_FIELDWIDTH)-1)<<OSCL_DIS_BITPOS )
#define EN_OSCL_SYNC_BITPOS ( 4 )
#define EN_OSCL_SYNC_FIELDWIDTH ( 1 )
#define EN_OSCL_SYNC_MASK ( ((1<<EN_OSCL_SYNC_FIELDWIDTH)-1)<<EN_OSCL_SYNC_BITPOS )
#define DIS_SYN_PDN_OSCH_BITPOS ( 7 )
#define DIS_SYN_PDN_OSCH_FIELDWIDTH ( 1 )
#define DIS_SYN_PDN_OSCH_MASK ( ((1<<DIS_SYN_PDN_OSCH_FIELDWIDTH)-1)<<DIS_SYN_PDN_OSCH_BITPOS )
#define SEL1_CLK_BIOZ_BITPOS ( 8 )
#define SEL1_CLK_BIOZ_FIELDWIDTH ( 1 )
#define SEL1_CLK_BIOZ_MASK ( ((1<<SEL1_CLK_BIOZ_FIELDWIDTH)-1)<<SEL1_CLK_BIOZ_BITPOS )
#define SEL2_CLK_BIOZ_BITPOS ( 9 )
#define SEL2_CLK_BIOZ_FIELDWIDTH ( 1 )
#define SEL2_CLK_BIOZ_MASK ( ((1<<SEL2_CLK_BIOZ_FIELDWIDTH)-1)<<SEL2_CLK_BIOZ_BITPOS )
#define EN_PLL_BITPOS ( 10 )
#define EN_PLL_FIELDWIDTH ( 1 )
#define EN_PLL_MASK ( ((1<<EN_PLL_FIELDWIDTH)-1)<<EN_PLL_BITPOS )
#define SEL1_CLK_RAC_BITPOS ( 12 )
#define SEL1_CLK_RAC_FIELDWIDTH ( 1 )
#define SEL1_CLK_RAC_MASK ( ((1<<SEL1_CLK_RAC_FIELDWIDTH)-1)<<SEL1_CLK_RAC_BITPOS )
#define SEL2_CLK_RAC_BITPOS ( 13 )
#define SEL2_CLK_RAC_FIELDWIDTH ( 1 )
#define SEL2_CLK_RAC_MASK ( ((1<<SEL2_CLK_RAC_FIELDWIDTH)-1)<<SEL2_CLK_RAC_BITPOS )
#define DIV_TE_RAC_OUT_EN_BITPOS ( 16 )
#define DIV_TE_RAC_OUT_EN_FIELDWIDTH ( 1 )
#define DIV_TE_RAC_OUT_EN_MASK ( ((1<<DIV_TE_RAC_OUT_EN_FIELDWIDTH)-1)<<DIV_TE_RAC_OUT_EN_BITPOS )

#define CONFIG_CLK_DIV_MIX1_ADDR ( 192 )
#define DIV_IN_BIOZ_BITPOS ( 4 )
#define DIV_IN_BIOZ_FIELDWIDTH ( 3 )
#define DIV_IN_BIOZ_MASK ( ((1<<DIV_IN_BIOZ_FIELDWIDTH)-1)<<DIV_IN_BIOZ_BITPOS )
#define DIV_FB_PLL_BITPOS ( 9 )
#define DIV_FB_PLL_FIELDWIDTH ( 5 )
#define DIV_FB_PLL_MASK ( ((1<<DIV_FB_PLL_FIELDWIDTH)-1)<<DIV_FB_PLL_BITPOS )
#define DIV_OUT_BIOZ_BITPOS ( 14 )
#define DIV_OUT_BIOZ_FIELDWIDTH ( 4 )
#define DIV_OUT_BIOZ_MASK ( ((1<<DIV_OUT_BIOZ_FIELDWIDTH)-1)<<DIV_OUT_BIOZ_BITPOS )
#define DIV_OUT_RAC_BITPOS ( 20 )
#define DIV_OUT_RAC_FIELDWIDTH ( 2 )
#define DIV_OUT_RAC_MASK ( ((1<<DIV_OUT_RAC_FIELDWIDTH)-1)<<DIV_OUT_RAC_BITPOS )

#define CONFIG_PRPCT_MIX1_ADDR ( 193 )
#define COUNT_RAC_BITPOS ( 0 )
#define COUNT_RAC_FIELDWIDTH ( 16 )
#define COUNT_RAC_MASK ( ((1<<COUNT_RAC_FIELDWIDTH)-1)<<COUNT_RAC_BITPOS )

#define CONFIG_TS_1TO8_MIX1_ADDR ( 194 )
#define CONFIG_TS0_BITPOS ( 0 )
#define CONFIG_TS0_FIELDWIDTH ( 3 )
#define CONFIG_TS0_MASK ( ((1<<CONFIG_TS0_FIELDWIDTH)-1)<<CONFIG_TS0_BITPOS )
#define CONFIG_TS1_BITPOS ( 3 )
#define CONFIG_TS1_FIELDWIDTH ( 3 )
#define CONFIG_TS1_MASK ( ((1<<CONFIG_TS1_FIELDWIDTH)-1)<<CONFIG_TS1_BITPOS )
#define CONFIG_TS2_BITPOS ( 6 )
#define CONFIG_TS2_FIELDWIDTH ( 3 )
#define CONFIG_TS2_MASK ( ((1<<CONFIG_TS2_FIELDWIDTH)-1)<<CONFIG_TS2_BITPOS )
#define CONFIG_TS3_BITPOS ( 9 )
#define CONFIG_TS3_FIELDWIDTH ( 3 )
#define CONFIG_TS3_MASK ( ((1<<CONFIG_TS3_FIELDWIDTH)-1)<<CONFIG_TS3_BITPOS )
#define CONFIG_TS4_BITPOS ( 12 )
#define CONFIG_TS4_FIELDWIDTH ( 3 )
#define CONFIG_TS4_MASK ( ((1<<CONFIG_TS4_FIELDWIDTH)-1)<<CONFIG_TS4_BITPOS )
#define CONFIG_TS5_BITPOS ( 15 )
#define CONFIG_TS5_FIELDWIDTH ( 3 )
#define CONFIG_TS5_MASK ( ((1<<CONFIG_TS5_FIELDWIDTH)-1)<<CONFIG_TS5_BITPOS )
#define CONFIG_TS6_BITPOS ( 18 )
#define CONFIG_TS6_FIELDWIDTH ( 3 )
#define CONFIG_TS6_MASK ( ((1<<CONFIG_TS6_FIELDWIDTH)-1)<<CONFIG_TS6_BITPOS )
#define CONFIG_TS7_BITPOS ( 21 )
#define CONFIG_TS7_FIELDWIDTH ( 3 )
#define CONFIG_TS7_MASK ( ((1<<CONFIG_TS7_FIELDWIDTH)-1)<<CONFIG_TS7_BITPOS )

#define CONFIG_TS_9TO16_MIX1_ADDR ( 195 )
#define CONFIG_TS8_BITPOS ( 0 )
#define CONFIG_TS8_FIELDWIDTH ( 3 )
#define CONFIG_TS8_MASK ( ((1<<CONFIG_TS8_FIELDWIDTH)-1)<<CONFIG_TS8_BITPOS )
#define CONFIG_TS9_BITPOS ( 3 )
#define CONFIG_TS9_FIELDWIDTH ( 3 )
#define CONFIG_TS9_MASK ( ((1<<CONFIG_TS9_FIELDWIDTH)-1)<<CONFIG_TS9_BITPOS )
#define CONFIG_TS10_BITPOS ( 6 )
#define CONFIG_TS10_FIELDWIDTH ( 3 )
#define CONFIG_TS10_MASK ( ((1<<CONFIG_TS10_FIELDWIDTH)-1)<<CONFIG_TS10_BITPOS )
#define CONFIG_TS11_BITPOS ( 9 )
#define CONFIG_TS11_FIELDWIDTH ( 3 )
#define CONFIG_TS11_MASK ( ((1<<CONFIG_TS11_FIELDWIDTH)-1)<<CONFIG_TS11_BITPOS )
#define CONFIG_TS12_BITPOS ( 12 )
#define CONFIG_TS12_FIELDWIDTH ( 3 )
#define CONFIG_TS12_MASK ( ((1<<CONFIG_TS12_FIELDWIDTH)-1)<<CONFIG_TS12_BITPOS )
#define CONFIG_TS13_BITPOS ( 15 )
#define CONFIG_TS13_FIELDWIDTH ( 3 )
#define CONFIG_TS13_MASK ( ((1<<CONFIG_TS13_FIELDWIDTH)-1)<<CONFIG_TS13_BITPOS )
#define CONFIG_TS14_BITPOS ( 18 )
#define CONFIG_TS14_FIELDWIDTH ( 3 )
#define CONFIG_TS14_MASK ( ((1<<CONFIG_TS14_FIELDWIDTH)-1)<<CONFIG_TS14_BITPOS )
#define CONFIG_TS15_BITPOS ( 21 )
#define CONFIG_TS15_FIELDWIDTH ( 3 )
#define CONFIG_TS15_MASK ( ((1<<CONFIG_TS15_FIELDWIDTH)-1)<<CONFIG_TS15_BITPOS )

#define CONFIG_NUM_TS_MIX1_ADDR ( 196 )
#define REG_NUM_TS_BITPOS ( 0 )
#define REG_NUM_TS_FIELDWIDTH ( 4 )
#define REG_NUM_TS_MASK ( ((1<<REG_NUM_TS_FIELDWIDTH)-1)<<REG_NUM_TS_BITPOS )
#define REG_NUM_ESAW_BITPOS ( 4 )
#define REG_NUM_ESAW_FIELDWIDTH ( 6 )
#define REG_NUM_ESAW_MASK ( ((1<<REG_NUM_ESAW_FIELDWIDTH)-1)<<REG_NUM_ESAW_BITPOS )
#define REG_NUM_BSAW_BITPOS ( 10 )
#define REG_NUM_BSAW_FIELDWIDTH ( 6 )
#define REG_NUM_BSAW_MASK ( ((1<<REG_NUM_BSAW_FIELDWIDTH)-1)<<REG_NUM_BSAW_BITPOS )

#define CONFIG_ECG1_MIX1_ADDR ( 200 )
#define SW_ECG_INP_ECG_BITPOS ( 0 )
#define SW_ECG_INP_ECG_FIELDWIDTH ( 4 )
#define SW_ECG_INP_ECG_MASK ( ((1<<SW_ECG_INP_ECG_FIELDWIDTH)-1)<<SW_ECG_INP_ECG_BITPOS )
#define SW_ECG_INM_ECG_BITPOS ( 4 )
#define SW_ECG_INM_ECG_FIELDWIDTH ( 4 )
#define SW_ECG_INM_ECG_MASK ( ((1<<SW_ECG_INM_ECG_FIELDWIDTH)-1)<<SW_ECG_INM_ECG_BITPOS )
#define SW_RLD_BITPOS ( 8 )
#define SW_RLD_FIELDWIDTH ( 4 )
#define SW_RLD_MASK ( ((1<<SW_RLD_FIELDWIDTH)-1)<<SW_RLD_BITPOS )
#define SHORT_ECG_INM_RLD_BITPOS ( 12 )
#define SHORT_ECG_INM_RLD_FIELDWIDTH ( 1 )
#define SHORT_ECG_INM_RLD_MASK ( ((1<<SHORT_ECG_INM_RLD_FIELDWIDTH)-1)<<SHORT_ECG_INM_RLD_BITPOS )
#define SHORT_ECG_INP_RLD_BITPOS ( 13 )
#define SHORT_ECG_INP_RLD_FIELDWIDTH ( 1 )
#define SHORT_ECG_INP_RLD_MASK ( ((1<<SHORT_ECG_INP_RLD_FIELDWIDTH)-1)<<SHORT_ECG_INP_RLD_BITPOS )
#define CONFIG_RLD_AS_UGB_BITPOS ( 14 )
#define CONFIG_RLD_AS_UGB_FIELDWIDTH ( 1 )
#define CONFIG_RLD_AS_UGB_MASK ( ((1<<CONFIG_RLD_AS_UGB_FIELDWIDTH)-1)<<CONFIG_RLD_AS_UGB_BITPOS )
#define RLD_FILT_BYP_BITPOS ( 15 )
#define RLD_FILT_BYP_FIELDWIDTH ( 1 )
#define RLD_FILT_BYP_MASK ( ((1<<RLD_FILT_BYP_FIELDWIDTH)-1)<<RLD_FILT_BYP_BITPOS )
#define RLD_DISCONNECT_BITPOS ( 16 )
#define RLD_DISCONNECT_FIELDWIDTH ( 1 )
#define RLD_DISCONNECT_MASK ( ((1<<RLD_DISCONNECT_FIELDWIDTH)-1)<<RLD_DISCONNECT_BITPOS )
#define ECG_INA_GAIN_BITPOS ( 17 )
#define ECG_INA_GAIN_FIELDWIDTH ( 3 )
#define ECG_INA_GAIN_MASK ( ((1<<ECG_INA_GAIN_FIELDWIDTH)-1)<<ECG_INA_GAIN_BITPOS )
#define DIS_CHOP_INA1_BITPOS ( 21 )
#define DIS_CHOP_INA1_FIELDWIDTH ( 1 )
#define DIS_CHOP_INA1_MASK ( ((1<<DIS_CHOP_INA1_FIELDWIDTH)-1)<<DIS_CHOP_INA1_BITPOS )

#define CONFIG_ECG2_MIX1_ADDR ( 201 )
#define EN_DEC_ECG_BITPOS ( 9 )
#define EN_DEC_ECG_FIELDWIDTH ( 1 )
#define EN_DEC_ECG_MASK ( ((1<<EN_DEC_ECG_FIELDWIDTH)-1)<<EN_DEC_ECG_BITPOS )
#define ECG_DEC_FACTOR_BITPOS ( 10 )
#define ECG_DEC_FACTOR_FIELDWIDTH ( 3 )
#define ECG_DEC_FACTOR_MASK ( ((1<<ECG_DEC_FACTOR_FIELDWIDTH)-1)<<ECG_DEC_FACTOR_BITPOS )
#define SW_ECG_INP_RESP_BITPOS ( 16 )
#define SW_ECG_INP_RESP_FIELDWIDTH ( 4 )
#define SW_ECG_INP_RESP_MASK ( ((1<<SW_ECG_INP_RESP_FIELDWIDTH)-1)<<SW_ECG_INP_RESP_BITPOS )
#define SW_ECG_INM_RESP_BITPOS ( 20 )
#define SW_ECG_INM_RESP_FIELDWIDTH ( 4 )
#define SW_ECG_INM_RESP_MASK ( ((1<<SW_ECG_INM_RESP_FIELDWIDTH)-1)<<SW_ECG_INM_RESP_BITPOS )

#define CONFIG_ECG_CH2_ADDR ( 202 )
#define EN_ECG2_BITPOS ( 0 )
#define EN_ECG2_FIELDWIDTH ( 1 )
#define EN_ECG2_MASK ( ((1<<EN_ECG2_FIELDWIDTH)-1)<<EN_ECG2_BITPOS )
#define SEL_IN_BIOZ_RX_BITPOS ( 1 )
#define SEL_IN_BIOZ_RX_FIELDWIDTH ( 1 )
#define SEL_IN_BIOZ_RX_MASK ( ((1<<SEL_IN_BIOZ_RX_FIELDWIDTH)-1)<<SEL_IN_BIOZ_RX_BITPOS )
#define EN_RLD_LOOP_ECG2_BITPOS ( 2 )
#define EN_RLD_LOOP_ECG2_FIELDWIDTH ( 1 )
#define EN_RLD_LOOP_ECG2_MASK ( ((1<<EN_RLD_LOOP_ECG2_FIELDWIDTH)-1)<<EN_RLD_LOOP_ECG2_BITPOS )
#define RECONFIGURE_BIOZ_LPF_BITPOS ( 3 )
#define RECONFIGURE_BIOZ_LPF_FIELDWIDTH ( 1 )
#define RECONFIGURE_BIOZ_LPF_MASK ( ((1<<RECONFIGURE_BIOZ_LPF_FIELDWIDTH)-1)<<RECONFIGURE_BIOZ_LPF_BITPOS )
#define DIS_CHOP_INA2_BITPOS ( 4 )
#define DIS_CHOP_INA2_FIELDWIDTH ( 1 )
#define DIS_CHOP_INA2_MASK ( ((1<<DIS_CHOP_INA2_FIELDWIDTH)-1)<<DIS_CHOP_INA2_BITPOS )

#define CONFIG_BIA_SW_MATRIX_STATIC_MIX1_ADDR ( 203 )
#define SW_BIOZ_TXP_BITPOS ( 0 )
#define SW_BIOZ_TXP_FIELDWIDTH ( 4 )
#define SW_BIOZ_TXP_MASK ( ((1<<SW_BIOZ_TXP_FIELDWIDTH)-1)<<SW_BIOZ_TXP_BITPOS )
#define SW_BIOZ_TXM_BITPOS ( 4 )
#define SW_BIOZ_TXM_FIELDWIDTH ( 4 )
#define SW_BIOZ_TXM_MASK ( ((1<<SW_BIOZ_TXM_FIELDWIDTH)-1)<<SW_BIOZ_TXM_BITPOS )
#define SW_BIOZ_RXP_BITPOS ( 8 )
#define SW_BIOZ_RXP_FIELDWIDTH ( 4 )
#define SW_BIOZ_RXP_MASK ( ((1<<SW_BIOZ_RXP_FIELDWIDTH)-1)<<SW_BIOZ_RXP_BITPOS )
#define SW_BIOZ_RXM_BITPOS ( 12 )
#define SW_BIOZ_RXM_FIELDWIDTH ( 4 )
#define SW_BIOZ_RXM_MASK ( ((1<<SW_BIOZ_RXM_FIELDWIDTH)-1)<<SW_BIOZ_RXM_BITPOS )

#define CONFIG_BIA_EXC_MIX1_ADDR ( 204 )
#define BIOZ_PHI_STEP_BITPOS ( 0 )
#define BIOZ_PHI_STEP_FIELDWIDTH ( 20 )
#define BIOZ_PHI_STEP_MASK ( ((1<<BIOZ_PHI_STEP_FIELDWIDTH)-1)<<BIOZ_PHI_STEP_BITPOS )
#define BIOZ_CORDIC_DIS_BITPOS ( 22 )
#define BIOZ_CORDIC_DIS_FIELDWIDTH ( 1 )
#define BIOZ_CORDIC_DIS_MASK ( ((1<<BIOZ_CORDIC_DIS_FIELDWIDTH)-1)<<BIOZ_CORDIC_DIS_BITPOS )
#define BIOZ_EXC_SQUARE_BITPOS ( 23 )
#define BIOZ_EXC_SQUARE_FIELDWIDTH ( 1 )
#define BIOZ_EXC_SQUARE_MASK ( ((1<<BIOZ_EXC_SQUARE_FIELDWIDTH)-1)<<BIOZ_EXC_SQUARE_BITPOS )

#define CONFIG_BIA_TX_MIX1_ADDR ( 205 )
#define BIOZ_RE_BITPOS ( 0 )
#define BIOZ_RE_FIELDWIDTH ( 5 )
#define BIOZ_RE_MASK ( ((1<<BIOZ_RE_FIELDWIDTH)-1)<<BIOZ_RE_BITPOS )
#define BIOZ_CE_BITPOS ( 5 )
#define BIOZ_CE_FIELDWIDTH ( 3 )
#define BIOZ_CE_MASK ( ((1<<BIOZ_CE_FIELDWIDTH)-1)<<BIOZ_CE_BITPOS )
#define SHORT_RINT_BIOZ_BITPOS ( 10 )
#define SHORT_RINT_BIOZ_FIELDWIDTH ( 1 )
#define SHORT_RINT_BIOZ_MASK ( ((1<<SHORT_RINT_BIOZ_FIELDWIDTH)-1)<<SHORT_RINT_BIOZ_BITPOS )
#define ATTN_BIOZ_TX_BITPOS ( 11 )
#define ATTN_BIOZ_TX_FIELDWIDTH ( 3 )
#define ATTN_BIOZ_TX_MASK ( ((1<<ATTN_BIOZ_TX_FIELDWIDTH)-1)<<ATTN_BIOZ_TX_BITPOS )

#define CONFIG_BIA_RX_MIX1_ADDR ( 206 )
#define SEL_CHPF1_BIOZ_BITPOS ( 1 )
#define SEL_CHPF1_BIOZ_FIELDWIDTH ( 1 )
#define SEL_CHPF1_BIOZ_MASK ( ((1<<SEL_CHPF1_BIOZ_FIELDWIDTH)-1)<<SEL_CHPF1_BIOZ_BITPOS )
#define BYP_CHPF1_BIOZ_BITPOS ( 2 )
#define BYP_CHPF1_BIOZ_FIELDWIDTH ( 1 )
#define BYP_CHPF1_BIOZ_MASK ( ((1<<BYP_CHPF1_BIOZ_FIELDWIDTH)-1)<<BYP_CHPF1_BIOZ_BITPOS )
#define SEL_RHPF1_BIOZ_BITPOS ( 3 )
#define SEL_RHPF1_BIOZ_FIELDWIDTH ( 2 )
#define SEL_RHPF1_BIOZ_MASK ( ((1<<SEL_RHPF1_BIOZ_FIELDWIDTH)-1)<<SEL_RHPF1_BIOZ_BITPOS )
#define DIS_RHPF1_BIOZ_BITPOS ( 5 )
#define DIS_RHPF1_BIOZ_FIELDWIDTH ( 1 )
#define DIS_RHPF1_BIOZ_MASK ( ((1<<DIS_RHPF1_BIOZ_FIELDWIDTH)-1)<<DIS_RHPF1_BIOZ_BITPOS )
#define BIOZ_INA_GAIN_BITPOS ( 7 )
#define BIOZ_INA_GAIN_FIELDWIDTH ( 3 )
#define BIOZ_INA_GAIN_MASK ( ((1<<BIOZ_INA_GAIN_FIELDWIDTH)-1)<<BIOZ_INA_GAIN_BITPOS )
#define BIOZ_LPF_BW_BITPOS ( 11 )
#define BIOZ_LPF_BW_FIELDWIDTH ( 2 )
#define BIOZ_LPF_BW_MASK ( ((1<<BIOZ_LPF_BW_FIELDWIDTH)-1)<<BIOZ_LPF_BW_BITPOS )
#define SHORT_BIOZ_INP_RLD_BITPOS ( 17 )
#define SHORT_BIOZ_INP_RLD_FIELDWIDTH ( 1 )
#define SHORT_BIOZ_INP_RLD_MASK ( ((1<<SHORT_BIOZ_INP_RLD_FIELDWIDTH)-1)<<SHORT_BIOZ_INP_RLD_BITPOS )
#define SHORT_BIOZ_INM_RLD_BITPOS ( 18 )
#define SHORT_BIOZ_INM_RLD_FIELDWIDTH ( 1 )
#define SHORT_BIOZ_INM_RLD_MASK ( ((1<<SHORT_BIOZ_INM_RLD_FIELDWIDTH)-1)<<SHORT_BIOZ_INM_RLD_BITPOS )

#define CONFIG_BIA_PROC_MIX1_ADDR ( 207 )
#define PROCESS_BSAW_BITPOS ( 2 )
#define PROCESS_BSAW_FIELDWIDTH ( 2 )
#define PROCESS_BSAW_MASK ( ((1<<PROCESS_BSAW_FIELDWIDTH)-1)<<PROCESS_BSAW_BITPOS )
#define EN_DEC_BIOZ_BITPOS ( 4 )
#define EN_DEC_BIOZ_FIELDWIDTH ( 1 )
#define EN_DEC_BIOZ_MASK ( ((1<<EN_DEC_BIOZ_FIELDWIDTH)-1)<<EN_DEC_BIOZ_BITPOS )
#define BIOZ_DEC_FACTOR_BITPOS ( 5 )
#define BIOZ_DEC_FACTOR_FIELDWIDTH ( 3 )
#define BIOZ_DEC_FACTOR_MASK ( ((1<<BIOZ_DEC_FACTOR_FIELDWIDTH)-1)<<BIOZ_DEC_FACTOR_BITPOS )

#define CONFIG_ELECTRODE_BIAS1_MIX1_ADDR ( 212 )
#define SW_RBIAS1_ECGP_BITPOS ( 0 )
#define SW_RBIAS1_ECGP_FIELDWIDTH ( 1 )
#define SW_RBIAS1_ECGP_MASK ( ((1<<SW_RBIAS1_ECGP_FIELDWIDTH)-1)<<SW_RBIAS1_ECGP_BITPOS )
#define SW_RBIAS1_RLD_BITPOS ( 2 )
#define SW_RBIAS1_RLD_FIELDWIDTH ( 1 )
#define SW_RBIAS1_RLD_MASK ( ((1<<SW_RBIAS1_RLD_FIELDWIDTH)-1)<<SW_RBIAS1_RLD_BITPOS )
#define SW_RBIAS1_LEAD_BIAS_BITPOS ( 3 )
#define SW_RBIAS1_LEAD_BIAS_FIELDWIDTH ( 1 )
#define SW_RBIAS1_LEAD_BIAS_MASK ( ((1<<SW_RBIAS1_LEAD_BIAS_FIELDWIDTH)-1)<<SW_RBIAS1_LEAD_BIAS_BITPOS )
#define POL_RBIAS1_LEAD_BIAS_BITPOS ( 4 )
#define POL_RBIAS1_LEAD_BIAS_FIELDWIDTH ( 1 )
#define POL_RBIAS1_LEAD_BIAS_MASK ( ((1<<POL_RBIAS1_LEAD_BIAS_FIELDWIDTH)-1)<<POL_RBIAS1_LEAD_BIAS_BITPOS )
#define SW_RBIAS2_ECGM_BITPOS ( 5 )
#define SW_RBIAS2_ECGM_FIELDWIDTH ( 1 )
#define SW_RBIAS2_ECGM_MASK ( ((1<<SW_RBIAS2_ECGM_FIELDWIDTH)-1)<<SW_RBIAS2_ECGM_BITPOS )
#define SW_RBIAS2_RLD_BITPOS ( 7 )
#define SW_RBIAS2_RLD_FIELDWIDTH ( 1 )
#define SW_RBIAS2_RLD_MASK ( ((1<<SW_RBIAS2_RLD_FIELDWIDTH)-1)<<SW_RBIAS2_RLD_BITPOS )
#define SW_RBIAS2_LEAD_BIAS_BITPOS ( 8 )
#define SW_RBIAS2_LEAD_BIAS_FIELDWIDTH ( 1 )
#define SW_RBIAS2_LEAD_BIAS_MASK ( ((1<<SW_RBIAS2_LEAD_BIAS_FIELDWIDTH)-1)<<SW_RBIAS2_LEAD_BIAS_BITPOS )
#define POL_RBIAS2_LEAD_BIAS_BITPOS ( 9 )
#define POL_RBIAS2_LEAD_BIAS_FIELDWIDTH ( 1 )
#define POL_RBIAS2_LEAD_BIAS_MASK ( ((1<<POL_RBIAS2_LEAD_BIAS_FIELDWIDTH)-1)<<POL_RBIAS2_LEAD_BIAS_BITPOS )
#define SW_RBIAS3_ECG1_BITPOS ( 10 )
#define SW_RBIAS3_ECG1_FIELDWIDTH ( 2 )
#define SW_RBIAS3_ECG1_MASK ( ((1<<SW_RBIAS3_ECG1_FIELDWIDTH)-1)<<SW_RBIAS3_ECG1_BITPOS )
#define SW_RBIAS3_RLD_BITPOS ( 12 )
#define SW_RBIAS3_RLD_FIELDWIDTH ( 1 )
#define SW_RBIAS3_RLD_MASK ( ((1<<SW_RBIAS3_RLD_FIELDWIDTH)-1)<<SW_RBIAS3_RLD_BITPOS )
#define SW_RBIAS3_LEAD_BIAS_BITPOS ( 13 )
#define SW_RBIAS3_LEAD_BIAS_FIELDWIDTH ( 1 )
#define SW_RBIAS3_LEAD_BIAS_MASK ( ((1<<SW_RBIAS3_LEAD_BIAS_FIELDWIDTH)-1)<<SW_RBIAS3_LEAD_BIAS_BITPOS )
#define POL_RBIAS3_LEAD_BIAS_BITPOS ( 14 )
#define POL_RBIAS3_LEAD_BIAS_FIELDWIDTH ( 1 )
#define POL_RBIAS3_LEAD_BIAS_MASK ( ((1<<POL_RBIAS3_LEAD_BIAS_FIELDWIDTH)-1)<<POL_RBIAS3_LEAD_BIAS_BITPOS )
#define SW_RBIAS4_ECG2_BITPOS ( 15 )
#define SW_RBIAS4_ECG2_FIELDWIDTH ( 2 )
#define SW_RBIAS4_ECG2_MASK ( ((1<<SW_RBIAS4_ECG2_FIELDWIDTH)-1)<<SW_RBIAS4_ECG2_BITPOS )
#define SW_BRIAS4_RLD_BITPOS ( 17 )
#define SW_BRIAS4_RLD_FIELDWIDTH ( 1 )
#define SW_BRIAS4_RLD_MASK ( ((1<<SW_BRIAS4_RLD_FIELDWIDTH)-1)<<SW_BRIAS4_RLD_BITPOS )
#define SW_RBIAS4_LEAD_BIAS_BITPOS ( 18 )
#define SW_RBIAS4_LEAD_BIAS_FIELDWIDTH ( 1 )
#define SW_RBIAS4_LEAD_BIAS_MASK ( ((1<<SW_RBIAS4_LEAD_BIAS_FIELDWIDTH)-1)<<SW_RBIAS4_LEAD_BIAS_BITPOS )
#define POL_RBIAS4_LEAD_BIAS_BITPOS ( 19 )
#define POL_RBIAS4_LEAD_BIAS_FIELDWIDTH ( 1 )
#define POL_RBIAS4_LEAD_BIAS_MASK ( ((1<<POL_RBIAS4_LEAD_BIAS_FIELDWIDTH)-1)<<POL_RBIAS4_LEAD_BIAS_BITPOS )

#define CONFIG_ELECTRODE_BIAS2_MIX1_ADDR ( 213 )
#define SEL_RBIAS_CH1_BITPOS ( 0 )
#define SEL_RBIAS_CH1_FIELDWIDTH ( 4 )
#define SEL_RBIAS_CH1_MASK ( ((1<<SEL_RBIAS_CH1_FIELDWIDTH)-1)<<SEL_RBIAS_CH1_BITPOS )
#define SEL_RBIAS_CH2_BITPOS ( 4 )
#define SEL_RBIAS_CH2_FIELDWIDTH ( 4 )
#define SEL_RBIAS_CH2_MASK ( ((1<<SEL_RBIAS_CH2_FIELDWIDTH)-1)<<SEL_RBIAS_CH2_BITPOS )

#define CONFIG_COMP_ANA_MIX1_ADDR ( 214 )
#define EN_COMP_ANA_BITPOS ( 0 )
#define EN_COMP_ANA_FIELDWIDTH ( 1 )
#define EN_COMP_ANA_MASK ( ((1<<EN_COMP_ANA_FIELDWIDTH)-1)<<EN_COMP_ANA_BITPOS )
#define AC_LEAD_DET_CLK_PHASE_BITPOS ( 1 )
#define AC_LEAD_DET_CLK_PHASE_FIELDWIDTH ( 1 )
#define AC_LEAD_DET_CLK_PHASE_MASK ( ((1<<AC_LEAD_DET_CLK_PHASE_FIELDWIDTH)-1)<<AC_LEAD_DET_CLK_PHASE_BITPOS )
#define LEAD_DET_THR_L_BITPOS ( 2 )
#define LEAD_DET_THR_L_FIELDWIDTH ( 4 )
#define LEAD_DET_THR_L_MASK ( ((1<<LEAD_DET_THR_L_FIELDWIDTH)-1)<<LEAD_DET_THR_L_BITPOS )
#define LEAD_DET_THR_H_BITPOS ( 6 )
#define LEAD_DET_THR_H_FIELDWIDTH ( 4 )
#define LEAD_DET_THR_H_MASK ( ((1<<LEAD_DET_THR_H_FIELDWIDTH)-1)<<LEAD_DET_THR_H_BITPOS )
#define LEAD_DET_WIDTH_BITPOS ( 14 )
#define LEAD_DET_WIDTH_FIELDWIDTH ( 8 )
#define LEAD_DET_WIDTH_MASK ( ((1<<LEAD_DET_WIDTH_FIELDWIDTH)-1)<<LEAD_DET_WIDTH_BITPOS )
#define LEAD_DET_MODULE_CLK_EN_BITPOS ( 22 )
#define LEAD_DET_MODULE_CLK_EN_FIELDWIDTH ( 1 )
#define LEAD_DET_MODULE_CLK_EN_MASK ( ((1<<LEAD_DET_MODULE_CLK_EN_FIELDWIDTH)-1)<<LEAD_DET_MODULE_CLK_EN_BITPOS )

#define CONFIG_IACTIVE_MIX1_ADDR ( 215 )
#define IBIAS_AMPL_BITPOS ( 0 )
#define IBIAS_AMPL_FIELDWIDTH ( 3 )
#define IBIAS_AMPL_MASK ( ((1<<IBIAS_AMPL_FIELDWIDTH)-1)<<IBIAS_AMPL_BITPOS )
#define IBIAS_BIAS_AMPL_BITPOS ( 3 )
#define IBIAS_BIAS_AMPL_FIELDWIDTH ( 5 )
#define IBIAS_BIAS_AMPL_MASK ( ((1<<IBIAS_BIAS_AMPL_FIELDWIDTH)-1)<<IBIAS_BIAS_AMPL_BITPOS )
#define SW_IBIAS_AC_BITPOS ( 12 )
#define SW_IBIAS_AC_FIELDWIDTH ( 1 )
#define SW_IBIAS_AC_MASK ( ((1<<SW_IBIAS_AC_FIELDWIDTH)-1)<<SW_IBIAS_AC_BITPOS )
#define EN_AC_LEAD_DET_CLK_BITPOS ( 14 )
#define EN_AC_LEAD_DET_CLK_FIELDWIDTH ( 1 )
#define EN_AC_LEAD_DET_CLK_MASK ( ((1<<EN_AC_LEAD_DET_CLK_FIELDWIDTH)-1)<<EN_AC_LEAD_DET_CLK_BITPOS )
#define EN_IBIAS_BITPOS ( 15 )
#define EN_IBIAS_FIELDWIDTH ( 1 )
#define EN_IBIAS_MASK ( ((1<<EN_IBIAS_FIELDWIDTH)-1)<<EN_IBIAS_BITPOS )

#define CONFIG_COMP_DIG_MIX1_ADDR ( 216 )
#define AC_LEAD_DET_THR_L_BITPOS ( 0 )
#define AC_LEAD_DET_THR_L_FIELDWIDTH ( 8 )
#define AC_LEAD_DET_THR_L_MASK ( ((1<<AC_LEAD_DET_THR_L_FIELDWIDTH)-1)<<AC_LEAD_DET_THR_L_BITPOS )
#define AC_LEAD_DET_THR_H_BITPOS ( 12 )
#define AC_LEAD_DET_THR_H_FIELDWIDTH ( 11 )
#define AC_LEAD_DET_THR_H_MASK ( ((1<<AC_LEAD_DET_THR_H_FIELDWIDTH)-1)<<AC_LEAD_DET_THR_H_BITPOS )

#define CONFIG_PACE_DETECT_ADDR ( 218 )
#define EN_PACE_BITPOS ( 0 )
#define EN_PACE_FIELDWIDTH ( 1 )
#define EN_PACE_MASK ( ((1<<EN_PACE_FIELDWIDTH)-1)<<EN_PACE_BITPOS )
#define EN_PACE_COMP2_BITPOS ( 1 )
#define EN_PACE_COMP2_FIELDWIDTH ( 1 )
#define EN_PACE_COMP2_MASK ( ((1<<EN_PACE_COMP2_FIELDWIDTH)-1)<<EN_PACE_COMP2_BITPOS )
#define PACE_REF1_H_BITPOS ( 3 )
#define PACE_REF1_H_FIELDWIDTH ( 3 )
#define PACE_REF1_H_MASK ( ((1<<PACE_REF1_H_FIELDWIDTH)-1)<<PACE_REF1_H_BITPOS )
#define PACE_REF2_H_BITPOS ( 6 )
#define PACE_REF2_H_FIELDWIDTH ( 3 )
#define PACE_REF2_H_MASK ( ((1<<PACE_REF2_H_FIELDWIDTH)-1)<<PACE_REF2_H_BITPOS )
#define PACE_REF1_L_BITPOS ( 9 )
#define PACE_REF1_L_FIELDWIDTH ( 3 )
#define PACE_REF1_L_MASK ( ((1<<PACE_REF1_L_FIELDWIDTH)-1)<<PACE_REF1_L_BITPOS )
#define PACE_REF2_L_BITPOS ( 12 )
#define PACE_REF2_L_FIELDWIDTH ( 3 )
#define PACE_REF2_L_MASK ( ((1<<PACE_REF2_L_FIELDWIDTH)-1)<<PACE_REF2_L_BITPOS )

#define CONFIG_PACE_SIG_CHAIN_ADDR ( 219 )
#define PACE_CONFIG_REG0_BITPOS ( 0 )
#define PACE_CONFIG_REG0_FIELDWIDTH ( 24 )
#define PACE_CONFIG_REG0_MASK ( ((1<<PACE_CONFIG_REG0_FIELDWIDTH)-1)<<PACE_CONFIG_REG0_BITPOS )

#define CONFIG_PACE_DIG_REG1_ADDR ( 220 )
#define WIDTH_PACE_MIN_BITPOS ( 0 )
#define WIDTH_PACE_MIN_FIELDWIDTH ( 6 )
#define WIDTH_PACE_MIN_MASK ( ((1<<WIDTH_PACE_MIN_FIELDWIDTH)-1)<<WIDTH_PACE_MIN_BITPOS )
#define WIDTH_PACE_MAX_BITPOS ( 6 )
#define WIDTH_PACE_MAX_FIELDWIDTH ( 8 )
#define WIDTH_PACE_MAX_MASK ( ((1<<WIDTH_PACE_MAX_FIELDWIDTH)-1)<<WIDTH_PACE_MAX_BITPOS )
#define PACE_OBS_EXTEND_BITPOS ( 14 )
#define PACE_OBS_EXTEND_FIELDWIDTH ( 2 )
#define PACE_OBS_EXTEND_MASK ( ((1<<PACE_OBS_EXTEND_FIELDWIDTH)-1)<<PACE_OBS_EXTEND_BITPOS )
#define SEL_CLK_PACE_BITPOS ( 16 )
#define SEL_CLK_PACE_FIELDWIDTH ( 2 )
#define SEL_CLK_PACE_MASK ( ((1<<SEL_CLK_PACE_FIELDWIDTH)-1)<<SEL_CLK_PACE_BITPOS )
#define PACE_VALID_COMPLETE_BITPOS ( 18 )
#define PACE_VALID_COMPLETE_FIELDWIDTH ( 1 )
#define PACE_VALID_COMPLETE_MASK ( ((1<<PACE_VALID_COMPLETE_FIELDWIDTH)-1)<<PACE_VALID_COMPLETE_BITPOS )
#define PACE_LOCKOUT_TIME_BITPOS ( 19 )
#define PACE_LOCKOUT_TIME_FIELDWIDTH ( 5 )
#define PACE_LOCKOUT_TIME_MASK ( ((1<<PACE_LOCKOUT_TIME_FIELDWIDTH)-1)<<PACE_LOCKOUT_TIME_BITPOS )

#define CONFIG_PACE_DIG_REG2_ADDR ( 221 )
#define PACE_CONFIG_REG1_BITPOS ( 0 )
#define PACE_CONFIG_REG1_FIELDWIDTH ( 24 )
#define PACE_CONFIG_REG1_MASK ( ((1<<PACE_CONFIG_REG1_FIELDWIDTH)-1)<<PACE_CONFIG_REG1_BITPOS )

#define CONFIG_PACE_DIG_REG3_ADDR ( 222 )
#define PACE_CONFIG_REG2_BITPOS ( 0 )
#define PACE_CONFIG_REG2_FIELDWIDTH ( 24 )
#define PACE_CONFIG_REG2_MASK ( ((1<<PACE_CONFIG_REG2_FIELDWIDTH)-1)<<PACE_CONFIG_REG2_BITPOS )

#define READ_PACE_STATUS_ADDR ( 227 )
#define PACE_DETECTED_BITPOS ( 0 )
#define PACE_DETECTED_FIELDWIDTH ( 1 )
#define PACE_DETECTED_MASK ( ((1<<PACE_DETECTED_FIELDWIDTH)-1)<<PACE_DETECTED_BITPOS )
#define PACE_POLARITY_BITPOS ( 1 )
#define PACE_POLARITY_FIELDWIDTH ( 1 )
#define PACE_POLARITY_MASK ( ((1<<PACE_POLARITY_FIELDWIDTH)-1)<<PACE_POLARITY_BITPOS )

#define READ_PACE_STATUS2_ADDR ( 228 )
#define PACE_DETECTED2_BITPOS ( 0 )
#define PACE_DETECTED2_FIELDWIDTH ( 1 )
#define PACE_DETECTED2_MASK ( ((1<<PACE_DETECTED2_FIELDWIDTH)-1)<<PACE_DETECTED2_BITPOS )

#define CONFIG_DDS_ADDR ( 251 )
#define BIOZ_PHASE_OFFSET_BITPOS ( 0 )
#define BIOZ_PHASE_OFFSET_FIELDWIDTH ( 12 )
#define BIOZ_PHASE_OFFSET_MASK ( ((1<<BIOZ_PHASE_OFFSET_FIELDWIDTH)-1)<<BIOZ_PHASE_OFFSET_BITPOS )
#define FORCE_BIOZ_TX_DAC_BITPOS ( 15 )
#define FORCE_BIOZ_TX_DAC_FIELDWIDTH ( 1 )
#define FORCE_BIOZ_TX_DAC_MASK ( ((1<<FORCE_BIOZ_TX_DAC_FIELDWIDTH)-1)<<FORCE_BIOZ_TX_DAC_BITPOS )
#define BIOZ_TX_DAC_TO_FORCE_BITPOS ( 17 )
#define BIOZ_TX_DAC_TO_FORCE_FIELDWIDTH ( 7 )
#define BIOZ_TX_DAC_TO_FORCE_MASK ( ((1<<BIOZ_TX_DAC_TO_FORCE_FIELDWIDTH)-1)<<BIOZ_TX_DAC_TO_FORCE_BITPOS )

#define AFE_FIFO_ADDR ( 255 )

#endif